FROM node:8
MAINTAINER James Lamb <jaylamb20@gmail.com>


# Add Python 3 to this thang
RUN apt-get update && \
  apt-get install -y python3-pip python3-dev && \
  cd /usr/local/bin && \
  ln -s /usr/bin/python3 python && \
  pip3 install --upgrade pip && \
  rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED 1

# Copy Flask app stuff into the container
RUN mkdir -p /opt/services/flaskapp/src
ADD ./ui /opt/services/flaskapp/src/
ADD ./resume_parsing /opt/services/flaskapp/src
EXPOSE 5090

# Install deps
RUN pip install \
    Flask \
    flask_cors

# Change dirs to wherever the flask code is
WORKDIR /opt/services/flaskapp/src

# Build the application
RUN cd frontend/ && \
    npm install && \
    npm run build && \
    rm -rf node_modules && \
    cd ..

FROM continuum:miniconda3
# setup conda env
RUN conda-env create -n resume_parsing -f env.yml
RUN source activate resume_parsing

RUN python -m spacy download en && \
    python -m nltk.downloader stopwords

RUN python -m nltk.downloader stopwords

#CMD python /opt/services/flaskapp/src/resume_parsing/get_models.py
CMD python /opt/services/flaskapp/src/app.py
