FROM python:3
MAINTAINER James Lamb <jaylamb20@gmail.com>

ENV PYTHONUNBUFFERED 1

# Copy Flask app stuff into the container
RUN mkdir -p /opt/services/flaskapp/src
ADD . /opt/services/flaskapp/src/
EXPOSE 5090

# Install deps
RUN pip install Flask

# Change dirs to wherever the flask code is
WORKDIR /opt/services/flaskapp/src

CMD python /opt/services/flaskapp/src/app.py
