FROM node:8
MAINTAINER James Lamb <jaylamb20@gmail.com>

# Add Python 3 to this thang
RUN apt-get update && \
    apt-get install -y python3-pip python3-dev && \
    cd /usr/local/bin && \
    ln -s /usr/bin/python3 python && \
    pip3 install --upgrade pip && \
    rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED 1

# Copy Flask app stuff + models into the container
RUN mkdir -p /opt/services/flaskapp/src
COPY . /opt/services/flaskapp/src/
EXPOSE 5090

# Get other Python deps deps
RUN pip install \
    # flask deps \
    Flask \
    flask_cors \
    # modeling deps \
    nltk \
    spacy \
    gensim \
    simplejson && \
    python -m spacy download en && \
    python -m nltk.downloader stopwords

# Change dirs to wherever the flask code is
WORKDIR /opt/services/flaskapp/src

# Create a jinja template out of the LDA viz.
# Yes this is a hack but all great things are
RUN touch frontend/lda.html && \
    echo "{% extends \"layout.html\" %}" >> frontend/lda.html && \
    echo "{% block content %}" >> frontend/lda.html && \
    echo "<br>" >> frontend/lda.html && \
    cat models/lda.html >> frontend/lda.html && \
    echo "{% endblock %}" >> frontend/lda.html


# Build the application
RUN cd frontend/ && \
    npm install && \
    npm run build && \
    rm -rf node_modules && \
    cd ..

CMD python /opt/services/flaskapp/src/app.py
